import './extensions.js';

import '/imports/startup/both/loggingSetup.js';

import LoggerModule from '/imports/lib/Logger.js';
const log = LoggerModule.Logger.for('main');

import assertSecureConfigModule from './lib/assertSecureConfig.js';
const { checkProductionAuthConfig } = assertSecureConfigModule;

// Log immediately to see if we're reaching this point
log.info('==========================================================================================');
log.info('Starting server initialization...', { TEST_RUN: process.env.TEST_RUN, ENABLE_SYNCED_CRON: process.env.ENABLE_SYNCED_CRON });
log.info('==========================================================================================');

// Initialize global.Collections early so packages can check for its existence
global.Collections = {};

// import './ServerSideRendering.js';
// import './AccountsServer.js';
// import './SmartHealthCards.js';
// import './ProxyMethods.js';
// import './ProxyHttpRelay.js';

// import './WebsocketPublications.js';
// import './HipaaLogging.js';

// need to upgrade mongoose, mongo, and the kerberose dependency
// then we can re-enable
// import './FhirSchemaImporter.js';

import './Cron.js';
import './ConsentEngineMethods.js';
import './SearchParameterMethods.js';
import './SyntheaMethods.js';
import './RadiologyCatalogInitializer.js';
import './ConsentEngineHttp.js';
import './SocialMediaMeta.js';
import './CdsHooksEndpoints.js';
import './Methods.js';
import './Metadata.js';
import './RestEndpoints.js';
import './BulkData.js';  // Must be before FhirEndpoints (catch-all handler)
import './FhirEndpoints.js';
import './OAuthEndpoints.js';
// import './DebugCommunications.js';
// import './DebugInterventions.js';
import './ProxyRelay.js';
import './VaultServer.js';
import '../imports/lib/UdapMethods.js';
import './Swagger.js';
import './AccountsMethods.js';
import './DicomEndpoints.js';

// ServerMethods registry + JSON-RPC transport — MUST load before the
// workflow server-loader so packages can Meteor.ServerMethods.define()
import './rpc/rpcSetup.js';

// Import workflow server methods and hooks (auto-generated by rspack.workflowParser.js)
import { initializeWorkflowHooks } from '@workflows/server-loader.js';

// GridFS Manager for DICOM file storage
import GridFSManager from './lib/GridFSManager.js';

import './lib/loggingMethods.js';

// Reference ranges seeder
import { seedReferenceRanges } from './referenceRanges/seed.js';

// Import accounts startup if enabled
import '../imports/startup/server/index.js';

// Import API methods
import '../imports/api/activityDefinitions/methods.js';
import '../imports/api/allergyIntolerances/methods.js';
import '../imports/api/appointments/methods.js';
import '../imports/api/AuditEvents/AuditEvents'; // Import the methods
import '../imports/api/carePlans/methods.js';
import '../imports/api/careTeams/methods.js';
import '../imports/api/rfc7523/methods.js';
import '../imports/api/communications/methods.js';
import '../imports/api/compositions/methods.js';
import '../imports/api/share/methods.js';
import '../imports/api/conditions/methods.js';
import '../imports/api/consents/methods.js';
import '../imports/api/dicom/server/methods.js';
import '../imports/api/documentReferences/methods.js';
import '../imports/api/devices/methods.js'; // Import the methods
import '../imports/api/encounters/methods.js';
import '../imports/api/episodeOfCares/methods.js';
import '../imports/api/endpoints/methods.js';
import '../imports/api/molecularSequences/methods.js';
import '../imports/api/imagingStudies/methods.js';
import '../imports/api/locations/methods.js';
import '../imports/api/observations/methods.js';
import '/server/referenceRanges/methods';
import '../imports/api/organizations/methods.js';
import '../imports/api/healthcareServices/methods.js';
import '../imports/api/insurancePlans/methods.js';
import '../imports/methods/immunizations.js';
import '../imports/api/medicationAdministrations/methods.js';
import '../imports/api/medicationRequests/methods.js';
import '../imports/api/medications/methods.js';
import '../imports/api/medias/methods.js';
import '../imports/api/measures/methods.js';
import '../imports/api/measureReports/methods.js';
import '../imports/api/messageHeaders/methods.js';
import '../imports/api/nutritionIntakes/methods.js';
import '../imports/api/nutritionOrders/methods.js';
import '../imports/api/nutritionProducts/methods.js';
import '../imports/api/patients/methods.js';
import '../imports/api/planDefinitions/methods.js';
import '../imports/api/practitioners/methods.js';
import '../imports/api/practitionerRoles/methods.js';
import '../imports/api/procedures/methods.js';
import '../imports/api/questionnaires/methods.js';
import '../imports/api/questionnaireResponses/methods.js';
import '../imports/api/researchSubjects/methods.js';
import '../imports/api/research-studies/methods.js';
import '../imports/api/schedules/methods.js';
import '../imports/api/serviceRequests/methods.js';
import '../imports/api/specimens/methods.js';
import '../imports/api/substances/methods.js';
import '../imports/api/diagnosticReports/methods.js';
import '../imports/api/bodyStructures/methods.js';
import '../imports/api/clinicalImpressions/methods.js';
import '../imports/api/riskAssessments/methods.js';
import '../imports/api/supplyRequests/methods.js';
import '../imports/methods/supplyDeliveries.js';
import '../imports/api/groups/methods.js';
import '../imports/api/lists/methods.js';
import '../imports/api/rxnorm/methods.js';
import '../imports/api/oauthClients/methods.js';
import '../imports/methods/tasks.js';
import '../imports/api/serverConfiguration/methods.js';

// Import test methods (for non-production environments)
import '../imports/accounts/server/test-methods.js';
import '../imports/accounts/server/methods.js';

// Import publications
import './publications/autopublish.js';
import './publications/selectedPatient.js';
import './publications/patients.js';
import './publications/conditions.js';
import './publications/communications.js';
import './publications/serviceRequests.js';

// Import practitioner startup (includes methods and publications)
import './startup/practitionerStartup.js';

// Ensure MongoDB indexes on patient-scoped clinical collections
import './startup/ensureClinicalIndexes.js';

// Verify observations setup (development only)
import './verify-observations.js';

// Import FHIR methods
import '../imports/methods/fhirResourceStatistics.js';

// Import publications (including autopublish if enabled)
import './publications/autopublish.js';


import { Meteor } from 'meteor/meteor';
import { Random } from 'meteor/random';
import { WebApp } from 'meteor/webapp';
import { get } from 'lodash';

import mongoose from 'mongoose';
import { Mongo } from '@accounts/mongo';
import { AccountsServer } from '@accounts/server';

import { LinksCollection } from '/imports/collections/LinksCollection';
import { OAuthClients } from '/imports/collections/OAuthClients';
import { ConnectedSources } from '/imports/collections/ConnectedSources';

// Patient Records Connect — SMART standalone patient launch + OAuth callback.
// Settings-gated via settings.private.smartConnect (methods throw
// feature-disabled when off).
import './connect/methods.js';
import './connect/launchHandlers.js';

// Self-distribution update check — one startup ping of the homepage's
// /releases.json. Settings-gated via settings.public.updates.
import './UpdateChecker.js';


//===============================================================================================================
// Data Cursors



import { ActivityDefinitions } from '../imports/lib/schemas/SimpleSchemas/ActivityDefinitions';
import { AllergyIntolerances } from '../imports/lib/schemas/SimpleSchemas/AllergyIntolerances';
import { Appointments } from '../imports/lib/schemas/SimpleSchemas/Appointments';
import { ArtifactAssessments } from '../imports/lib/schemas/SimpleSchemas/ArtifactAssessments';
import { AuditEvents } from '../imports/lib/schemas/SimpleSchemas/AuditEvents';
import { Bundles } from '../imports/lib/schemas/SimpleSchemas/Bundles';
import { BiologicallyDerivedProducts } from '../imports/lib/schemas/SimpleSchemas/BiologicallyDerivedProducts';
import { BodyStructures } from '../imports/lib/schemas/SimpleSchemas/BodyStructures';
import { CarePlans } from '../imports/lib/schemas/SimpleSchemas/CarePlans';
import { ClinicalImpressions } from '../imports/lib/schemas/SimpleSchemas/ClinicalImpressions';
import { CareTeams } from '../imports/lib/schemas/SimpleSchemas/CareTeams';
import { Claims } from '../imports/lib/schemas/SimpleSchemas/Claims';
import { CodeSystems } from '../imports/lib/schemas/SimpleSchemas/CodeSystems';
import { Conditions } from '../imports/lib/schemas/SimpleSchemas/Conditions';
import { Coverages } from '../imports/lib/schemas/SimpleSchemas/Coverages';
import { Consents } from '../imports/lib/schemas/SimpleSchemas/Consents';
import { Communications } from '../imports/lib/schemas/SimpleSchemas/Communications';
import { CommunicationRequests } from '../imports/lib/schemas/SimpleSchemas/CommunicationRequests';
import { Compositions } from '../imports/lib/schemas/SimpleSchemas/Compositions';
import { Devices } from '../imports/lib/schemas/SimpleSchemas/Devices';
import { DeviceUseStatements } from '../imports/lib/schemas/SimpleSchemas/DeviceUseStatements';
import { DiagnosticReports } from '../imports/lib/schemas/SimpleSchemas/DiagnosticReports';
import { DocumentReferences } from '../imports/lib/schemas/SimpleSchemas/DocumentReferences';
import { Encounters } from '../imports/lib/schemas/SimpleSchemas/Encounters';
import { EpisodeOfCares } from '../imports/lib/schemas/SimpleSchemas/EpisodeOfCares';
import { Endpoints } from '../imports/lib/schemas/SimpleSchemas/Endpoints';
import { Evidences } from '../imports/lib/schemas/SimpleSchemas/Evidences';
import { ExplanationOfBenefits } from '../imports/lib/schemas/SimpleSchemas/ExplanationOfBenefits';
import { Goals } from '../imports/lib/schemas/SimpleSchemas/Goals';
import { Groups } from '../imports/lib/schemas/SimpleSchemas/Groups';
import { GuidanceResponses } from '../imports/lib/schemas/SimpleSchemas/GuidanceResponses';
import { Citations } from '../imports/lib/schemas/SimpleSchemas/Citations';
import { DetectedIssues } from '../imports/lib/schemas/SimpleSchemas/DetectedIssues';
import { EvidenceVariables } from '../imports/lib/schemas/SimpleSchemas/EvidenceVariables';
import { Immunizations } from '../imports/lib/schemas/SimpleSchemas/Immunizations';
import { ImagingStudies } from '../imports/lib/schemas/SimpleSchemas/ImagingStudies';
import { Libraries } from '../imports/lib/schemas/SimpleSchemas/Libraries';
import { Lists } from '../imports/lib/schemas/SimpleSchemas/Lists';
import { Locations } from '../imports/lib/schemas/SimpleSchemas/Locations';
import { Medications } from '../imports/lib/schemas/SimpleSchemas/Medications';
import { MolecularSequences } from '../imports/lib/schemas/SimpleSchemas/MolecularSequences';
import { MedicationAdministrations } from '../imports/lib/schemas/SimpleSchemas/MedicationAdministrations';
import { MedicationDispenses } from '../imports/lib/schemas/SimpleSchemas/MedicationDispenses';
import { MedicationRequests } from '../imports/lib/schemas/SimpleSchemas/MedicationRequests';
import { MedicationStatements } from '../imports/lib/schemas/SimpleSchemas/MedicationStatements';
import { Measures } from '../imports/lib/schemas/SimpleSchemas/Measures';
import { MeasureReports } from '../imports/lib/schemas/SimpleSchemas/MeasureReports';
import { Medias } from '../imports/lib/schemas/SimpleSchemas/Medias';
import { MessageHeaders } from '../imports/lib/schemas/SimpleSchemas/MessageHeaders';
import { NutritionIntakes } from '../imports/lib/schemas/SimpleSchemas/NutritionIntakes';
import { NutritionOrders } from '../imports/lib/schemas/SimpleSchemas/NutritionOrders';
import { NutritionProducts } from '../imports/lib/schemas/SimpleSchemas/NutritionProducts';
import { OperationOutcomes } from '../imports/lib/schemas/SimpleSchemas/OperationOutcomes';
import { Organizations } from '../imports/lib/schemas/SimpleSchemas/Organizations';
import { HealthcareServices } from '../imports/lib/schemas/SimpleSchemas/HealthcareServices';
import { InsurancePlans } from '../imports/lib/schemas/SimpleSchemas/InsurancePlans';
import { Observations } from '../imports/lib/schemas/SimpleSchemas/Observations';
import { ObservationDefinitions } from '../imports/lib/schemas/SimpleSchemas/ObservationDefinitions';
import { Patients } from '../imports/lib/schemas/SimpleSchemas/Patients';
import { Persons } from '../imports/lib/schemas/SimpleSchemas/Persons';
import { PlanDefinitions } from '../imports/lib/schemas/SimpleSchemas/PlanDefinitions';
import { RelatedPersons } from '../imports/lib/schemas/SimpleSchemas/RelatedPersons';
import { Practitioners } from '../imports/lib/schemas/SimpleSchemas/Practitioners';
import { PractitionerRoles } from '../imports/lib/schemas/SimpleSchemas/PractitionerRoles';
import { Procedures } from '../imports/lib/schemas/SimpleSchemas/Procedures';
import { Provenances } from '../imports/lib/schemas/SimpleSchemas/Provenances';
import { Questionnaires } from '../imports/lib/schemas/SimpleSchemas/Questionnaires';
import { QuestionnaireResponses } from '../imports/lib/schemas/SimpleSchemas/QuestionnaireResponses';
import { ResearchStudies } from '../imports/lib/schemas/SimpleSchemas/ResearchStudies';
import { ResearchSubjects } from '../imports/lib/schemas/SimpleSchemas/ResearchSubjects';
import { RiskAssessments } from '../imports/lib/schemas/SimpleSchemas/RiskAssessments';
import { Schedules } from '../imports/lib/schemas/SimpleSchemas/Schedules';
import { SearchParameters } from '../imports/lib/schemas/SimpleSchemas/SearchParameters';
import { ServiceRequests } from '../imports/lib/schemas/SimpleSchemas/ServiceRequests';
import { Specimens } from '../imports/lib/schemas/SimpleSchemas/Specimens';
import { Substances } from '../imports/lib/schemas/SimpleSchemas/Substances';
import { SupplyRequests } from '../imports/lib/schemas/SimpleSchemas/SupplyRequests';
import { SupplyDeliveries } from '../imports/lib/schemas/SimpleSchemas/SupplyDeliveries';
import { Tasks } from '../imports/lib/schemas/SimpleSchemas/Tasks';
import { ValueSets } from '../imports/lib/schemas/SimpleSchemas/ValueSets';
import { ServerConfiguration } from '../imports/lib/schemas/SimpleSchemas/ServerConfiguration';

import { FhirUtilities } from '../imports/lib/FhirUtilities.js'
import { FhirDehydrator } from '../imports/lib/FhirDehydrator.js'
import { HipaaLogger } from '../imports/lib/HipaaLogger.js'

import { LayoutHelpers } from '../imports/lib/LayoutHelpers.js'

Meteor.Collections = {
  ActivityDefinitions,
  AllergyIntolerances,
  Appointments,
  ArtifactAssessments,
  AuditEvents,
  BiologicallyDerivedProducts,
  BodyStructures,
  Bundles,
  CarePlans,
  CareTeams,
  Claims,
  ClinicalImpressions,
  CodeSystems,
  Conditions,
  ConnectedSources,
  Consents,
  Coverages,
  Communications,
  CommunicationRequests,
  Compositions,
  Devices,
  DeviceUseStatements,
  DiagnosticReports,
  DocumentReferences,
  Encounters,
  EpisodeOfCares,
  Endpoints,
  Evidences,
  ExplanationOfBenefits,
  Goals,
  Groups,
  GuidanceResponses,
  Citations,
  DetectedIssues,
  EvidenceVariables,
  Immunizations,
  ImagingStudies,
  Libraries,
  Lists,
  Locations,
  Medications,
  MedicationAdministrations,
  MedicationDispenses,
  MedicationRequests,
  MedicationStatements,
  MessageHeaders,
  Measures,
  MeasureReports,
  Medias,
  MolecularSequences,
  HealthcareServices,
  InsurancePlans,
  NutritionIntakes,
  NutritionOrders,
  NutritionProducts,
  OperationOutcomes,
  Organizations,
  HealthcareServices,
  InsurancePlans,
  Observations,
  ObservationDefinitions,
  Patients,
  Persons,
  PlanDefinitions,
  Practitioners,
  PractitionerRoles,
  Procedures,
  Provenances,
  Questionnaires,
  QuestionnaireResponses,
  RelatedPersons,
  ResearchStudies,
  ResearchSubjects,
  RiskAssessments,
  Schedules,
  SearchParameters,
  ServerConfiguration,
  ServiceRequests,
  Specimens,
  Substances,
  SupplyDeliveries,
  SupplyRequests,
  Tasks,
  ValueSets
}

global.FhirUtilities = FhirUtilities;
global.FhirDehydrator = FhirDehydrator;
global.LayoutHelpers = LayoutHelpers;
global.HipaaLogger = HipaaLogger;

// Populate global.Collections with all FHIR resource collections
Object.assign(global.Collections, {
  ActivityDefinitions,
  AllergyIntolerances,
  Appointments,
  ArtifactAssessments,
  AuditEvents,
  BiologicallyDerivedProducts,
  BodyStructures,
  Bundles,
  CarePlans,
  CareTeams,
  Claims,
  ClinicalImpressions,
  CodeSystems,
  Conditions,
  ConnectedSources,
  Consents,
  Coverages,
  Communications,
  CommunicationRequests,
  Compositions,
  Devices,
  DeviceUseStatements,
  DiagnosticReports,
  DocumentReferences,
  Encounters,
  EpisodeOfCares,
  Endpoints,
  Evidences,
  ExplanationOfBenefits,
  Goals,
  Groups,
  GuidanceResponses,
  Citations,
  DetectedIssues,
  EvidenceVariables,
  Immunizations,
  ImagingStudies,
  Libraries,
  Lists,
  Locations,
  Medications,
  MedicationAdministrations,
  MedicationDispenses,
  MedicationRequests,
  MedicationStatements,
  MessageHeaders,
  Measures,
  MeasureReports,
  Medias,
  MolecularSequences,
  HealthcareServices,
  InsurancePlans,
  NutritionIntakes,
  NutritionOrders,
  NutritionProducts,
  OperationOutcomes,
  Organizations,
  HealthcareServices,
  InsurancePlans,
  Observations,
  ObservationDefinitions,
  Patients,
  Persons,
  PlanDefinitions,
  Practitioners,
  PractitionerRoles,
  Procedures,
  Provenances,
  Questionnaires,
  QuestionnaireResponses,
  RelatedPersons,
  ResearchStudies,
  ResearchSubjects,
  RiskAssessments,
  Schedules,
  SearchParameters,
  ServerConfiguration,
  ServiceRequests,
  Specimens,
  Substances,
  SupplyDeliveries,
  SupplyRequests,
  Tasks,
  ValueSets
});



// Initialize workflow collection hooks after collections are populated
Meteor.startup(function() {
  try {
    initializeWorkflowHooks();
  } catch (e) {
    log.error('Failed to initialize workflow hooks', { error: e && e.message, stack: e && e.stack });
  }
});

// CR-2 (security audit 2026-07-01): fail-closed config assertion. A PRODUCTION
// deployment must not ACCIDENTALLY boot with OAuth or access control disabled —
// that silently opens the FHIR API to unauthenticated access. Local dev
// (Meteor.isDevelopment) is never blocked; it legitimately runs disableOauth.
//
// An INTENTIONAL open sandbox (unauthenticated FHIR API by design — a supported
// deployment posture) declares itself via settings.private.fhir.openSandbox:true
// (or OPEN_SANDBOX=true). When declared, production boots normally with an
// informational notice. When NOT declared, auth-off in production is treated as
// an accident and the server refuses to boot.
Meteor.startup(function() {
  const settingsOpenSandbox =
    Meteor.settings && Meteor.settings.private && Meteor.settings.private.fhir &&
    Meteor.settings.private.fhir.openSandbox === true;
  const sandboxAcknowledged = settingsOpenSandbox || process.env.OPEN_SANDBOX === 'true';

  const configCheck = checkProductionAuthConfig({
    settings: Meteor.settings,
    isProduction: Meteor.isProduction,
    sandboxAcknowledged: sandboxAcknowledged
  });

  if (!configCheck.secure) {
    log.error('FATAL: refusing to boot — production deployment has authentication/access control disabled and is not declared an open sandbox', {
      violations: configCheck.violations,
      remedy: 'enable OAuth + access control for production, OR declare an intentional open sandbox via settings.private.fhir.openSandbox:true (or OPEN_SANDBOX=true)'
    });
    // Fail closed: do not serve requests with an accidentally-insecure config.
    process.exit(1);
  }

  if (configCheck.sandboxMode) {
    log.warn('Open sandbox mode: the FHIR API is UNAUTHENTICATED by configuration (settings.private.fhir.openSandbox)', {
      unauthenticated: configCheck.violations
    });
  }
});

global.Appointments = Appointments;
global.AuditEvents = AuditEvents;
global.Conditions = Conditions;
global.Claims = Claims;
global.Encounters = Encounters;
global.EpisodeOfCares = EpisodeOfCares;
global.Endpoints = Endpoints;
global.ExplanationOfBenefits = ExplanationOfBenefits;
global.Immunizations = Immunizations;
global.Observations = Observations;
global.Practitioners = Practitioners;
global.PractitionerRoles = PractitionerRoles;
global.Procedures = Procedures;
global.MedicationRequests = MedicationRequests;
global.Medications = Medications;
global.MeasureReports = MeasureReports;
global.Medias = Medias;
global.Patients = Patients;
global.Questionnaires = Questionnaires;
global.QuestionnaireResponses = QuestionnaireResponses;
global.Schedules = Schedules;
global.SearchParameters = SearchParameters;
global.LinksCollection = LinksCollection;

//===============================================================================================================

// Handle SyncedCron startup control
import { SyncedCron } from './SyncedCron.js';

// Control SyncedCron startup based on environment variables and settings
Meteor.startup(() => {
  log.info('==========================================================================================');
  log.info('[SyncedCron] Checking cron configuration...', {
    TEST_RUN: process.env.TEST_RUN,
    ENABLE_SYNCED_CRON: process.env.ENABLE_SYNCED_CRON,
    enableCronAutomation: Meteor.settings?.private?.enableCronAutomation,
    enableTaskManager: Meteor.settings?.private?.enableTaskManager
  });
  log.info('==========================================================================================');

  // Check multiple conditions for whether to start SyncedCron
  const shouldStartCron =
    // Explicitly enabled via environment variable
    process.env.ENABLE_SYNCED_CRON === 'true' ||
    // Enabled in settings but NOT in test mode
    (Meteor.settings?.private?.enableCronAutomation && !process.env.TEST_RUN) ||
    // Legacy check for enableTaskManager
    (Meteor.settings?.private?.enableTaskManager && !process.env.TEST_RUN);

  if (shouldStartCron) {
    log.info('[SyncedCron] Starting cron scheduler...');
    SyncedCron.start();
  } else {
    log.info('[SyncedCron] Cron scheduler DISABLED - will not start');
    // quave:synced-cron doesn't auto-start, so we don't need to stop it
  }
});

//===============================================================================================================

let accountsServer;
Meteor.startup(async function(){
  // Initialize GridFS for DICOM file storage
  const gridfsInitialized = GridFSManager.initialize();
  if (gridfsInitialized) {
    global.GridFSManager = GridFSManager;
    log.info('GridFSManager initialized and exposed on global.GridFSManager');
  } else {
    log.warn('GridFSManager failed to initialize - DICOM uploads will not work');
  }

  // Need to add a default language for accessibility purposes
  WebApp.addHtmlAttributeHook(function() {
    return {
      "lang": "en"
    }
  })

  // Handle NotAuthorized UI bypass environment variable
  if(process.env.NOT_AUTHORIZED_UI_BYPASS) {
    log.info('==========================================================================================');
    log.info('[NotAuthorized] UI Bypass is ENABLED via environment variable');
    log.info('[NotAuthorized] Setting Meteor.settings.public.NotAuthorizedUiBypass = true');
    log.info('==========================================================================================');
    
    // Ensure settings structure exists
    if (!Meteor.settings) {
      Meteor.settings = {};
    }
    if (!Meteor.settings.public) {
      Meteor.settings.public = {};
    }
    
    // Set the bypass flag
    Meteor.settings.public.NotAuthorizedUiBypass = true;
  }

  // Handle Synthea DB Utils environment variable
  if(process.env.ENABLE_SYNTHEA_DB_UTILS) {
    log.info('==========================================================================================');
    log.info('[Synthea] Database Utils are ENABLED via environment variable');
    log.info('[Synthea] Setting Meteor.settings.public.enableSyntheaDbUtils = true');
    log.info('==========================================================================================');
    
    // Ensure settings structure exists
    if (!Meteor.settings) {
      Meteor.settings = {};
    }
    if (!Meteor.settings.public) {
      Meteor.settings.public = {};
    }
    
    // Set the Synthea DB utils flag
    Meteor.settings.public.enableSyntheaDbUtils = true;
  }

  // Initialize Radiology Catalog (populate PlanDefinitions for CPOE Diagnostic Imaging)
  // ONC §170.315(a)(3) - CPOE Diagnostic Imaging
  if (process.env.INITIALIZE_RADIOLOGY_CATALOG ||
      get(Meteor, 'settings.private.fhir.autoPopulate.radiologyCatalog')) {
    log.info('==========================================================================================');
    log.info('[RadiologyCatalog] Initialization ENABLED');
    log.info('[RadiologyCatalog] Source: LOINC/RSNA Radiology Playbook (free, no CPT license)');
    log.info('==========================================================================================');

    const { RadiologyCatalogInitializer } = await import('./RadiologyCatalogInitializer.js');
    await RadiologyCatalogInitializer.initializeRadiologyCatalog();
  }

  // Seed reference ranges base layer (blood panel ObservationDefinitions)
  await seedReferenceRanges();

  // Establish a database connection
  mongoose.connect(process.env.MONGO_URL, {
    useUnifiedTopology: true,
    useNewUrlParser: true
  });

  const db = mongoose.connection;
  
  let accountsMongo = new Mongo(db, {
    // options
  });

  // Connect to the accounts server for authentication 
  accountsServer = new AccountsServer(
    {
      db: accountsMongo,
      tokenSecret: get(Meteor, 'settings.private.accountServerTokenSecret', Random.secret()) 
    }
  );
});

export async function parseRpcAuthorization(accessToken){
  log.debug('Parsing user authorization');

  let isAuthorized = true;

  if(get(Meteor, 'settings.private.accessControl.enableRpcAccessRestrictions')){
    log.debug('parseRpcAuthorization accessToken present', { hasToken: !!accessToken });

    try {
      const session = await accountsServer.findSessionByAccessToken(accessToken);
      log.debug('parseRpcAuthorization session', { found: !!session });

      // const sessionUser = await accountsServer.findUserById(userId);
      // log.debug('parseRpcAuthorization sessionUser', { found: !!sessionUser });

      if(session){
        isAuthorized = true;
      }
    } catch (error) {
      log.error('findSessionByAccessToken error', { error: error && error.message });
      isAuthorized = false;
    }
  }
  return isAuthorized;
}




async function insertLink({ title, url }) {
  await LinksCollection.insertAsync({ title, url, createdAt: new Date() });
}

// Override Accounts.createUser to add detailed logging
const originalCreateUser = Accounts.createUser;
Accounts.createUser = function(options, callback) {
  log.debug('[Debug] Server Accounts.createUser called', { username: options.username, email: options.email, hasPassword: !!options.password });

  try {
    const result = originalCreateUser.call(this, options, callback);
    log.debug('[Debug] createUser succeeded', { result });
    return result;
  } catch (error) {
    log.error('[Debug] createUser error', { error: error && error.message, type: error && error.constructor && error.constructor.name, code: error && error.error, reason: error && error.reason });
    throw error;
  }
};

// Add test methods to verify accounts system.
//
// SECURITY GATE (july-fix-now #1): these expose anonymous account creation,
// user enumeration, and accounts-config disclosure, so they must NEVER ship
// in production. Registered only in development (meteor run — which is what
// CI uses) or when ENABLE_TEST_METHODS=true is set explicitly. No test suite
// references them (verified 2026-07-23); they are manual dev scaffolding.
if (Meteor.isDevelopment || process.env.ENABLE_TEST_METHODS === 'true') {
Meteor.methods({
  'test.accounts': function() {
    log.debug('[Test] Accounts test method called');
    return {
      success: true,
      accountsConfig: Accounts._options,
      timestamp: new Date()
    };
  },

  'test.createUser': function(userData) {
    log.debug('[Test] Creating user', { username: userData && userData.username });
    try {
      const userId = Accounts.createUser(userData);
      log.debug('[Test] User created', { userId });
      return { success: true, userId };
    } catch (error) {
      log.error('[Test] Create user error', { error: error && error.message });
      throw error;
    }
  },

  'test.checkExistingUser': async function(username, email) {
    log.debug('[Test] Checking for existing user', { username, email });

    const byUsername = await Meteor.users.findOneAsync({ username });
    const byEmail = await Meteor.users.findOneAsync({ 'emails.address': email });

    return {
      usernameExists: !!byUsername,
      emailExists: !!byEmail,
      userByUsername: byUsername ? { _id: byUsername._id, username: byUsername.username } : null,
      userByEmail: byEmail ? { _id: byEmail._id, emails: byEmail.emails } : null
    };
  },

  'test.listUsers': async function() {
    log.debug('[Test] Listing all users');
    const users = await Meteor.users.find({}, {
      fields: { username: 1, emails: 1, createdAt: 1 }
    }).fetchAsync();
    
    return users.map(u => ({
      _id: u._id,
      username: u.username,
      email: u.emails?.[0]?.address,
      createdAt: u.createdAt
    }));
  }
});
} else {
  log.info('test.* debug methods NOT registered (production; set ENABLE_TEST_METHODS=true to override)');
}

Meteor.startup(async () => {
  // If the Links collection is empty, add some data.
  if (await LinksCollection.find().countAsync() === 0) {
    await insertLink({
      title: 'Getting Started',
      url: '/getting-started'
    });

    await insertLink({
      title: 'Static Files',
      url: '/static-files'
    });

    await insertLink({
      title: 'SMART Launcher Debugger',
      url: '/smart-launcher-debugger'
    });

    await insertLink({
      title: 'SMART Sample App',
      url: '/smart-sample-app'
    });

    await insertLink({
      title: 'SMART App Debugger',
      url: '/smart-app-debugger'
    });

    await insertLink({
      title: 'Server Configuration',
      url: '/server-configuration'
    });

    await insertLink({
      title: 'UDAP Registration',
      url: '/udap-registration'
    });
  }

  // We publish the entire Links collection to all clients.
  // In order to be fetched in real-time to the clients
  Meteor.publish("links", function () {
    return LinksCollection.find();
  });

  Meteor.publish("OAuthClients", function () {
    return OAuthClients.find();
  });

  // Patient-specific OAuth authorizations publication
  // ONC g(10) 9.3.01 - Patient access to view authorized applications
  Meteor.publish('OAuthClients.forPatient', async function() {
    if (!this.userId) {
      return this.ready();
    }

    // Get user asynchronously for publication (Meteor v3)
    const user = await Meteor.users.findOneAsync({ _id: this.userId });
    const patientId = get(user, 'patientId');

    if (!patientId) {
      log.debug('OAuthClients.forPatient - No linked patient for user', { userId: this.userId });
      return this.ready();
    }

    // Return only active authorizations for this patient
    // Exclude sensitive fields (tokens, secrets)
    return OAuthClients.find(
      {
        patient_id: patientId,
        access_token: { $exists: true, $ne: null },
        revoked_at: { $exists: false }
      },
      {
        fields: {
          client_name: 1,
          client_id: 1,
          access_token_created_at: 1,
          created_at: 1,
          authorization_expires_at: 1,
          requested_scope: 1,
          scope: 1,
          launch_type: 1,
          patient_id: 1
          // Explicitly exclude: access_token, refresh_token, client_secret
        }
      }
    );
  });

});