Logical: Settings
Id: Settings
Title: "Settings"
Description: "Settings for Node on FHIR"
// * ^url = "http://hl7.org/fhir/tools/StructureDefinition/OAuthAuthenticationRequest"
// * ^version = "0.1.0"
// * ^status = #draft
// * ^publisher = "Example Publisher"
* public 1..1 SU BackboneElement "Public fields that are sent to the client"
  * title 0..1 string "Title of the application"
* public.theme 0..1 BackboneElement "Theme"
* public.theme.showVideoBackground 0..1 boolean "Video background is useful for telehealth and augmented reality apps."
* public.theme.defaultVideo 0..1 string "Path to default background video."
* public.theme.backgroundImagePath 0..1 string "Path to default background image."
* public.theme.palette 0..1 BackboneElement "Color palette"
* public.theme.palette.primaryColor 0..1 string "Hex color"
* public.theme.palette.primaryText 0..1 string "Hex color"
* public.theme.palette.secondaryColor 0..1 string "Hex color"
* public.theme.palette.secondaryText 0..1 string "Hex color"
* public.theme.palette.cardColor 0..1 string "Hex color"
* public.theme.palette.cardTextColor 0..1 string "Hex color"
* public.theme.palette.errorColor 0..1 string "Hex color"
* public.theme.palette.errorText 0..1 string "Hex color"
* public.theme.palette.appBarColor 0..1 string "Hex color"
* public.theme.palette.appBarTextColor 0..1 string "Hex color"
* public.theme.palette.paperColor 0..1 string "Hex color"
* public.theme.palette.paperTextColor 0..1 string "Hex color"
* public.theme.palette.bodyBackground 0..1 string "Hex color"
* public.theme.palette.canvasColor 0..1 string "Hex color"
* public.theme.palette.nivoTheme 0..1 string "Hex color"
* public.theme.grayscaleFilter 0..1 string "Hex color"
* public.loggingThreshold 0..1 string "Logging threshold determines how much data should be logged to the browser console."
* public.capabilityStatement 0..1 BackboneElement "Capability Statement parameters that will show up in /metadata route"
* public.capabilityStatement.resourceTypes 0..* string "Array of FHIR resourceTypes that the server supports"
* public.smartOnFhir 0..1 BackboneElement "SMART on FHIR launch context parameters (for launching from a clinical EHR)"
* public.smartOnFhir.vendor 0..1 string "Vendor"
* public.smartOnFhir.client_id 0..1 string "Client ID"
* public.smartOnFhir.scope 0..1 string "OAuth scopes"
* public.smartOnFhir.fhirServiceUrl 0..1 string "FHIR server URL"
* public.smartOnFhir.redirect_uri 0..1 string "Redirect URIs"
* public.smartOnFhir.iss 0..1 string "ISS value"
* public.smartOnFhir.autoDashboardNoDataPath 0..1 string "Default URL to recommend navigating to, when no data is loaded."
* public.socialmedia 0..1 BackboneElement "Parameters for registering with social media"
* public.socialmedia.title 0..1 string "Title to display on social media posts."
* public.socialmedia.type 0..1 string "Type of social media post."
* public.socialmedia.url 0..1 string "URL to link to from social media posts."
* public.socialmedia.image 0..1 string "Image to display on social media posts."
* public.socialmedia.description 0..1 string "Description to display on social media posts."
* public.socialmedia.site_name 0..1 string "Site name to display on social media posts."
* public.socialmedia.app_id 0..1 string "App ID to register with social media platform."
* public.defaults 0..1 BackboneElement "Default parameters"
* public.defaults.route 0..1 string ""
* public.defaults.landingPage 0..1 string ""
* public.defaults.homePage 0..1 string ""
* public.defaults.avatars 0..1 string ""
* public.defaults.barcodes 0..1 string ""
* public.defaults.dateFormat 0..1 string ""
* public.defaults.tableRowSize 0..1 string ""
* public.defaults.hexgridMenu 0..1 string ""
* public.defaults.nfcOrbital 0..1 string ""
* public.defaults.notificationMenu 0..1 string ""
* public.defaults.searchbarVisible 0..1 string ""
* public.defaults.prominantHeader 0..1 string ""
* public.defaults.showPatientNameInHeader 0..1 string ""
* public.defaults.displayUserNameInHeader 0..1 string ""
* public.defaults.enablePatientOveride 0..1 string ""
* public.defaults.viewportSafeArea 0..1 string ""
* public.defaults.displayNavbars 0..1 string ""
* public.defaults.disableHeader 0..1 string ""
* public.defaults.disableFooter 0..1 string ""
* public.defaults.disableCanvasSlide 0..1 string ""
* public.defaults.drawerWidth 0..1 string ""
* public.defaults.initialScale 0..1 string ""
* public.defaults.iFrameEnabled 0..1 string ""
* public.defaults.iFrameUrl 0..1 string ""
* public.defaults.defaultPagePadding 0..1 string ""
* public.defaults.paginationLimit 0..1 string ""
* public.defaults.subscriptionLimit 0..1 string ""
* public.defaults.unitsOfMeasure 0..1 string ""
* public.defaults.modals 0..1 BackboneElement "Modal dialogs"
* public.defaults.modals.maxWidth 0..1 string ""
* public.defaults.cards 0..1 BackboneElement "User interface cards"
* public.defaults.cards.height 0..1 string ""
* public.defaults.cards.opacity 0..1 string ""
* public.defaults.noData 0..1 BackboneElement "Content to display when no data is available"
* public.defaults.noData.title 0..1 string ""
* public.defaults.noData.subheader 0..1 string ""
* public.defaults.noData.buttonLabel 0..1 string ""
* public.defaults.noData.noDataImagePath 0..1 string ""
* public.defaults.noData.marginTop 0..1 string ""
* public.defaults.registration 0..1 BackboneElement "Registration dialog"
* public.defaults.registration.signInWith 0..1 boolean ""
* public.defaults.registration.displayFullLegalName 0..1 boolean ""
* public.defaults.registration.displayNickname 0..1 boolean ""
* public.defaults.registration.displayGivenAndFamily 0..1 boolean ""
* public.defaults.registration.displayFirstAndLast 0..1 boolean ""
* public.defaults.registration.displayUsername 0..1 boolean ""
* public.defaults.registration.displayEmail 0..1 boolean ""
* public.defaults.registration.displayPassword 0..1 boolean ""
* public.defaults.registration.displayInventationCode 0..1 boolean ""
* public.defaults.routes 0..1 BackboneElement "Client side user interface routes"
* public.defaults.routes.homePage 0..1 string ""
* public.defaults.routes.landingPage 0..1 string ""
* public.defaults.routes.adminWelcomePage 0..1 string ""
* public.defaults.routes.adminHomePage 0..1 string ""
* public.defaults.routes.adminDashboard 0..1 string ""
* public.defaults.header 0..1 BackboneElement "Header components"
* public.defaults.header.menuIcon 0..1 string ""
* public.defaults.header.patientId 0..1 string ""
* public.defaults.sidebar 0..1 BackboneElement "Sidebar parameters"
* public.defaults.sidebar.minibarVisible 0..1 string ""
* public.defaults.sidebar.menuItems 0..1 BackboneElement "Sidebar menu items"
* public.defaults.sidebar.menuItems.HomePage 0..1 string ""
* public.defaults.sidebar.menuItems.FhirResources 0..1 string ""
* public.defaults.sidebar.menuItems.DynamicModules 0..1 string ""
* public.defaults.sidebar.menuItems.SidebarWorkflows 0..1 string ""
* public.defaults.sidebar.menuItems.Theme 0..1 string ""
* public.defaults.sidebar.menuItems.About 0..1 string ""
* public.defaults.sidebar.menuItems.ConstructionZone 0..1 string ""
* public.defaults.sidebar.menuItems.Navbars 0..1 string ""
* public.defaults.sidebar.menuItems.DataImport 0..1 string ""
* public.defaults.sidebar.menuItems.DataExport 0..1 string ""
* public.defaults.sidebar.menuItems.HealthRecords 0..1 string ""
* public.defaults.sidebar.menuItems.Login 0..1 string ""
* public.defaults.sidebar.menuItems.Login.availability 0..1 string ""
* public.defaults.sidebar.menuItems.Registration 0..1 string ""
* public.defaults.sidebar.menuItems.Documentation 0..1 string ""
* public.defaults.sidebar.menuItems.Marketing 0..1 string ""
* public.defaults.sidebar.menuItems.TermsAndConditions 0..1 string ""
* public.defaults.sidebar.menuItems.Privacy 0..1 string ""
* public.defaults.sidebar.menuItems.QrScanner 0..1 string ""
* public.defaults.sidebar.hidden 0..1 string ""
* public.defaults.sidebar.adminHidden 0..1 string ""
* public.defaults.sidebar.hiddenWorkflow 0..1 string ""
* public.defaults.sidebar.links 0..1 BackboneElement "Documentation links"
* public.defaults.sidebar.links.documentation 0..1 string ""
* public.defaults.sidebar.customWorkflow 0..1 BackboneElement "Custom workflow parameters"
* public.defaults.sidebar.customWorkflow.label 0..1 string ""
* public.defaults.sidebar.customWorkflow.link 0..1 string ""
* public.defaults.sidebar.customWorkflow.icon 0..1 string ""
* public.defaults.sidebar.customSettings 0..1 BackboneElement "Custom settings parameters"
* public.defaults.sidebar.customSettings.label 0..1 string ""
* public.defaults.sidebar.customSettings.link 0..1 string ""
* public.defaults.sidebar.customSettings.icon 0..1 string ""
* public.healthrecords 0..1 BackboneElement "Health Records"
* public.healthrecords.suppressEmptyChartMessage 0..1 string ""
* public.google  0..1 BackboneElement "Google Products"
* public.google.analytics  0..1 BackboneElement "Google Analytics"
* public.google.analytics.trackingCode 0..1 string ""
* public.google.analytics.debug 0..1 string ""
* public.interfaces  0..1 BackboneElement "Interfaces"
* public.interfaces.default 0..1 BackboneElement "Default FHIR Server"
* public.interfaces.default.status 0..1 string ""
* public.interfaces.default.channel 0..1 BackboneElement "Communication Channels"
* public.interfaces.default.channel.endpoint 0..1 string ""
* public.interfaces.default.auth 0..1 BackboneElement "Channel authorization"
* public.interfaces.default.auth.username 0..1 string ""
* public.interfaces.default.auth.password 0..1 string ""
* public.interfaces.accountsServer  0..1 BackboneElement "Account Server"
* public.interfaces.accountsServer.database 0..1 string ""
* public.interfaces.accountsServer.host 0..1 string ""
* public.interfaces.accountsServer.port 0..1 string ""
* public.modules  0..1 BackboneElement "Modules (deprecated)"
* public.modules.data 0..1 string ""
* public.modules.forum 0..1 string ""
* public.modules.genome 0..1 string ""
* public.modules.healthlog 0..1 string ""
* public.modules.dermatograms 0..1 string ""
* public.modules.telemedicine 0..1 string ""
* public.modules.inbound 0..1 string ""
* public.modules.outbound 0..1 string ""
* public.modules.epic 0..1 string ""
* public.modules.statisticsLogging 0..1 string ""
* public.modules.app 0..1 BackboneElement "App Modules (deprecated)"
* public.modules.app.ChecklistManifesto 0..1 string ""
* public.modules.app.ContinuityOfCare 0..1 string ""
* public.modules.app.Videoconferencing 0..1 string ""
* public.modules.app.ZygoteAvatar 0..1 string ""
* public.modules.fhir 0..* BackboneElement "FHIR Workflows"
* public.modules.fhir.<fhirResource> 0..1 string ""
* public.modules.healthkit  0..1 BackboneElement "HealthKit"
* public.modules.healthkit.importDestination 0..1 string ""

* private 0..1 SU BackboneElement "Private fields that are only available on the server."
* private.debug 0..1 boolean "Synonym for DEBUG environment variable. (deprecated)"
* private.trace 0..1 boolean "Synonym for TRACE environment variable. (deprecated)"

* private.defaultUserRole 0..1 string "Default new user is assigned the 'patient' role."
* private.defaultClinicianRole 0..1 string "Default clinician user is assigned the 'healthcare practitioner' role."
* private.invitationCode 0..1 string "Default invitation code for new users is ''" // QWERTY - removed invitation code
* private.invitationExpiry 0..1 string "Default expiration date for invitation code."
* private.practitionerInvitationCode 0..1 string "Default clinician invitation code for new users is ''" // QWERTY - removed invitation code
* private.practitionerInvitationExpiry 0..1 string "Default expiration date for clinician invitation code."

* private.patientCreationOnSignupEnabled 0..1 boolean "Create a new FHIR Patient record when the user is created."
* private.practitionerCreationOnSignupEnabled 0..1 boolean "Create a new FHIR Practitioner record when the user is created."

* private.enableCronAutomation 0..1 boolean "Enables the built in timer mechanism that runs jobs on a scheduled basis."
* private.enableServerStats 0..1 boolean "Enables whether the server should generate statistics (every 5 mins)"
* private.recordVersioningEnabled 0..1 boolean "Record versioning determines whether a history of changes is kept."

* private.proxyServerEnabled 0..1 boolean "The FHIR Proxy service allows the server to relay requests on behalf of other systems."
* private.accountServerTokenSecret 0..1 string "The account server secret allows access token rotation."



* private.accessControl 0..1 BackboneElement "Access Control"
* private.accessControl.enableHttpAccessRestrictions 0..1 boolean "Enable access-control lists on HTTP interfaces."
* private.accessControl.enableRpcAccessRestrictions 0..1 boolean "Enable access-control lists on Meteor methods (RPC functions)."
* private.accessControl.enableEhrLaunchContext 0..1 boolean "Enable the app to be launched from an electronic health record (EHR)."
* private.accessControl.enableBasicAuth 0..1 boolean "Enable back-end services access via Basic Auth (minimal security; not recommended)."
* private.accessControl.enableJwtBackendServices 0..1 boolean "Enable back-end services access via JWT tokens (recommended)."
* private.accessControl.enableHipaaLogging 0..1 boolean "Enable the HIPAA Audit Log and logging on protected health information (PHI) access."
* private.accessControl.enableUnsafeProxy 0..1 boolean "Enable an open proxy relay service (exercise caution!)."

* private.x509 0..1 BackboneElement "X509 Security Infrastructure"
* private.x509.publicKey 0..1 BackboneElement "The x509 public key for the server."
* private.x509.privateKey 0..1 BackboneElement "The x509 private key for the server."
* private.x509.publicCertPem 0..1 BackboneElement "The x509 certificate for the server."

* private.fhir 0..1 BackboneElement "FHIR Server"
* private.fhir.disableOauth 0..1 boolean "Disable OAuth authorization (not the same as disabling access-control lists)."
* private.fhir.inboundQueue 0..1 boolean "Log all inbound requests to the InboundQueue collection."
* private.fhir.schemaValidation 0..1 BackboneElement "Validation enforces quality control and what data is allowed in/out of system"
* private.fhir.schemaValidation.filter 0..1 string ""
* private.fhir.schemaValidation.validate 0..1 string ""
* private.fhir.fhirPath 0..1 string "Defaults to '/baseR4'"

// * private.fhir.autoGenerateSubscriptionConfigs 0..1 string "If subscription autogeneration is not enabled, modules have to specify their own subscriptions."
* private.fhir.autoGeneratePublications 0..1 string "If publication autogeneration is not enabled, modules have to specify their own publications."
* private.fhir.autoGenerateSubscriptions 0..1 string "If subscription autogeneration is not enabled, modules have to specify their own subscriptions."
* private.fhir.publicationLimit 0..1 string "Defaults of 1000 records per collection get published to client"

* private.fhir.rest 0..* BackboneElement "REST Interactions"
* private.fhir.rest.AuditEvent 0..1 BackboneElement "HIPAA logging services"
* private.fhir.rest.AuditEvent.interactions 0..* string ""
* private.fhir.rest.AuditEvent.search 0..1 string ""
* private.fhir.rest.ValueSet 0..1 BackboneElement "Terminology services"
* private.fhir.rest.ValueSet.interactions 0..* string ""
* private.fhir.rest.ValueSet.search 0..1 string ""
